-- ############################################################
-- SECTION 1: Create Table (Fact+DIM)
-- ############################################################

CREATE OR REPLACE TABLE DEMO_PULS_SALES.P3_MART.FACT_SALES (
    ORDER_ID        STRING      NOT NULL,
    CUSTOMER_ID     STRING      NOT NULL,
    DATE_ID         DATE        NOT NULL,  
    REGION_CODE     STRING      NOT NULL,
    AMOUNT          NUMBER(18,2) NOT NULL
);

CREATE OR REPLACE TABLE DEMO_PULS_SALES.P3_MART.FACT_AR (
    AR_ID                STRING      NOT NULL,
    CUSTOMER_ID          STRING      NOT NULL,
    INVOICE_DATE_ID      DATE        NOT NULL,
    DUE_DATE_ID          DATE        NOT NULL,
    PAID_DATE_ID         DATE,       -- 可为空
    REGION_CODE          STRING      NOT NULL,
    AMOUNT               NUMBER(18,2) NOT NULL,
    IS_DUE_DATE_INVALID  BOOLEAN     NOT NULL
);

CREATE OR REPLACE TABLE DEMO_PULS_SALES.P3_MART.DIM_CUSTOMER (
    CUSTOMER_ID     STRING      NOT NULL,
    CUSTOMER_NAME   STRING      NOT NULL,
    IS_KA           BOOLEAN     NOT NULL,
    REGION_CODE     STRING      NOT NULL
);

CREATE OR REPLACE TABLE DEMO_PULS_SALES.P3_MART.DIM_DATE (
    DATE_ID     DATE       NOT NULL PRIMARY KEY,
    YEAR        NUMBER(4)  NOT NULL,
    MONTH       NUMBER(2)  NOT NULL,
    DAY         NUMBER(2)  NOT NULL,
    WEEKDAY     NUMBER(1)  NOT NULL,
    QUARTER     NUMBER(1)  NOT NULL
);

CREATE OR REPLACE TABLE DEMO_PULS_SALES.p3_MART.DIM_REGION (
    REGION_CODE     STRING      NOT NULL PRIMARY KEY,
    REGION_NAME     STRING      -- Optional description
);


INSERT INTO DEMO_PULS_SALES.MART.DIM_CUSTOMER (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    IS_KA,
    REGION_CODE
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    IS_KA,
    REGION_CODE
FROM DEMO_PULS_SALES.P2_STAGE.STG_CUSTOMER;

-- ############################################################
-- SECTION 2: Insert Data
-- ############################################################
--DIM.CUSTOMER
INSERT INTO DEMO_PULS_SALES.P3_MART.DIM_CUSTOMER (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    IS_KA,
    REGION_CODE
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    IS_KA,
    REGION_CODE
FROM DEMO_PULS_SALES.P2_STAGE.STG_CUSTOMER;

--DIM.DATE
INSERT INTO DEMO_PULS_SALES.P3_MART.DIM_DATE
WITH date_span AS (
  SELECT SEQ4() AS n
  FROM TABLE(GENERATOR(ROWCOUNT => 1461)) -- 4years
),
calendar AS (
  SELECT DATEADD(DAY, n, '2023-01-01') AS DATE_ID
  FROM date_span
)
SELECT
  DATE_ID,
  YEAR(DATE_ID) AS YEAR,
  MONTH(DATE_ID) AS MONTH,
  DAY(DATE_ID) AS DAY,
  DAYOFWEEK(DATE_ID) AS WEEKDAY,
  QUARTER(DATE_ID) AS QUARTER
FROM calendar;

--DIM.REGION
INSERT INTO DEMO_PULS_SALES.P3_MART.DIM_REGION (
    REGION_CODE,
    REGION_NAME
)
SELECT DISTINCT
    REGION_CODE,
    NULL AS REGION_NAME  
FROM DEMO_PULS_SALES.P2_STAGE.STG_CUSTOMER
WHERE REGION_CODE IS NOT NULL;

-- below for easy updates
UPDATE DEMO_PULS_SALES.P3_MART.DIM_REGION
SET REGION_NAME = CASE
    WHEN REGION_CODE = 'CN' THEN 'China'
    WHEN REGION_CODE = 'US' THEN 'United States'
    WHEN REGION_CODE = 'PL' THEN 'Poland'
    WHEN REGION_CODE = 'CZ' THEN 'Czech Republic'
    WHEN REGION_CODE = 'DE' THEN 'Germany'
    ELSE 'Unknown'
END;

--FACT.CUSTOMER
INSERT INTO DEMO_PULS_SALES.P3_MART.FACT_SALES (
    ORDER_ID,
    CUSTOMER_ID,
    DATE_ID,
    REGION_CODE,
    AMOUNT
)
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE AS DATE_ID,
    REGION_CODE,
    AMOUNT
FROM DEMO_PULS_SALES.P2_STAGE.STG_SO
WHERE ORDER_ID IS NOT NULL
  AND ORDER_DATE IS NOT NULL
  AND CUSTOMER_ID IS NOT NULL;

--fact.AR
INSERT INTO DEMO_PULS_SALES.P3_MART.FACT_AR (
    AR_ID,
    CUSTOMER_ID,
    INVOICE_DATE_ID,
    DUE_DATE_ID,
    PAID_DATE_ID,
    REGION_CODE,
    AMOUNT,
    IS_DUE_DATE_INVALID
)
SELECT
    l.AR_ID,
    l.CUSTOMER_ID,
    l.INVOICE_DATE,
    l.DUE_DATE,
    l.PAID_DATE,
    c.REGION_CODE,
    l.AMOUNT,
    l.IS_DUE_DATE_INVALID
FROM DEMO_PULS_SALES.P2_STAGE.STG_LEDGER l
LEFT JOIN DEMO_PULS_SALES.P2_STAGE.STG_CUSTOMER c
  ON l.CUSTOMER_ID = c.CUSTOMER_ID
WHERE l.AR_ID IS NOT NULL
  AND l.INVOICE_DATE IS NOT NULL
  AND l.DUE_DATE IS NOT NULL
ORDER BY AR_ID;

-- ############################################################
-- SECTION 3: Create Constraints (metadata)
-- ############################################################
--frquent used commands
--SHOW PRIMARY KEYS IN TABLE DEMO_PULS_SALES.P3_MART.FACT_AR;
--SHOW IMPORTED KEYS IN SCHEMA DEMO_PULS_SALES.P3_MART;
--ALTER TABLE DEMO_PULS_SALES.P3_MART.DIM_DATE DROP PRIMARY KEY;

-- DIM PK
ALTER TABLE DEMO_PULS_SALES.P3_MART.DIM_CUSTOMER ADD CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (CUSTOMER_ID);
ALTER TABLE DEMO_PULS_SALES.P3_MART.DIM_DATE ADD CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_ID);
ALTER TABLE DEMO_PULS_SALES.p3_MART.DIM_REGION ADD CONSTRAINT PK_DIM_REGION PRIMARY KEY (REGION_CODE);

-- FACT PK
ALTER TABLE DEMO_PULS_SALES.P3_MART.FACT_SALES ADD CONSTRAINT PK_FACT_SALES PRIMARY KEY (ORDER_ID);
ALTER TABLE DEMO_PULS_SALES.p3_MART.FACT_AR ADD CONSTRAINT PK_FACT_AR PRIMARY KEY (AR_ID);

-- DEFINE FK
-- FACT_SALES 
ALTER TABLE DEMO_PULS_SALES.p3_MART.FACT_SALES
  ADD CONSTRAINT FK_SALES_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES DEMO_PULS_SALES.P3_MART.DIM_CUSTOMER(CUSTOMER_ID);

ALTER TABLE DEMO_PULS_SALES.P3_MART.FACT_SALES
  ADD CONSTRAINT FK_SALES_DATE FOREIGN KEY (DATE_ID) REFERENCES DEMO_PULS_SALES.P3_MART.DIM_DATE(DATE_ID);

ALTER TABLE DEMO_PULS_SALES.P3_MART.FACT_SALES
  ADD CONSTRAINT FK_SALES_REGION FOREIGN KEY (REGION_CODE) REFERENCES DEMO_PULS_SALES.p3_MART.DIM_REGION(REGION_CODE);

-- FACT_AR 
ALTER TABLE DEMO_PULS_SALES.P3_MART.FACT_AR
  ADD CONSTRAINT FK_AR_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES DEMO_PULS_SALES.P3_MART.DIM_CUSTOMER(CUSTOMER_ID);

ALTER TABLE DEMO_PULS_SALES.P3_MART.FACT_AR
  ADD CONSTRAINT FK_AR_INVOICE_DATE FOREIGN KEY (INVOICE_DATE_ID) REFERENCES DEMO_PULS_SALES.P3_MART.DIM_DATE(DATE_ID);

ALTER TABLE DEMO_PULS_SALES.P3_MART.FACT_AR
  ADD CONSTRAINT FK_AR_DUE_DATE FOREIGN KEY (DUE_DATE_ID) REFERENCES DEMO_PULS_SALES.P3_MART.DIM_DATE(DATE_ID);

ALTER TABLE DEMO_PULS_SALES.P3_MART.FACT_AR
  ADD CONSTRAINT FK_AR_PAID_DATE FOREIGN KEY (PAID_DATE_ID) REFERENCES DEMO_PULS_SALES.P3_MART.DIM_DATE(DATE_ID);

ALTER TABLE DEMO_PULS_SALES.P3_MART.FACT_AR
  ADD CONSTRAINT FK_AR_REGION FOREIGN KEY (REGION_CODE) REFERENCES DEMO_PULS_SALES.P3_MART.DIM_REGION(REGION_CODE);
